# Generated by Django 6.0 on 2025-12-27 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_pdf', models.FileField(upload_to='input/')),
                ('updated_pdf', models.FileField(blank=True, null=True, upload_to='output/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
